name: Build and push reacts image

on: 
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: ECR Login
      id: login-pf-aws-ecr
      uses: aws-actions/amazon-ecr-login@v2
        
  
    - name: Build da imagem Docker
      env:
        ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry}}
        ECR_REPOSITORY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/pedritoreact
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
