name: Build and push React image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials and login to Amazon ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t ${{ steps.login-to-ecr.outputs.registry }}/${{ secrets.AWS_REPO }}:latest -f frontend/Dockerfile.yml ./frontend
          docker push ${{ steps.login-to-ecr.outputs.registry }}/${{ secrets.AWS_REPO }}:latest
