name: Build and push reacts image

on: 
  push:
    branches:
      - main
    paths:
    - 'frontend/**'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1


    - name: ECR Login
      uses: aws-actions/amazon-ecr-login@v2
        
  
    - name: Build da imagem Docker
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/pedritoreact:latest ./frontend
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/pedritoreact:latest
  
        
        
  
