name: Build and push reacts image

on: 
  push:
    branches:
      - main
    paths:
    - 'frontend/**'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Autenticando no Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Push da imagem no docker Hub
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.yml
        push: true
        tags: |
            pnunes276/zabbixstore-frontend:latest
            pnunes276/zabbixstore-frontend:v${{ github.run_number }}

    - name: ECR Login
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build da imagem Docker
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/pedritoreact:latest ./frontend
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/pedritoreact:latest
  
        
        
  
